# Generated by Django 5.0.2 on 2024-02-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_follower_followers_alter_follower_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
